//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IViewer.h
//  @ Date : 23/08/2009
//  @ Author : 
//
//


#if !defined(_IVIEWER_H)
#define _IVIEWER_H


class IViewer {
public:
        virtual void callRequestUserCode()=0;
        virtual void callDisplayUserProfile()=0;
};

#endif  //_IVIEWER_H
