//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Presenter.h
//  @ Date : 23/08/2009
//  @ Author : 
//
//


#if !defined(_PRESENTER_H)
#define _PRESENTER_H

#include "IViewer.h"

class Presenter {
public:
        void Presenter(IViewer* v);
	void start();
	list<string> loadListTypes();
	bool validate();
	void codeInputEnded();
	void loadProfile(string code);
private:
	string nom;
	string prenom;
	string type;
	string code;
	IViewer *viewer;

public :
         string get_nom() { return nom;}
        void set_nom(string v) { nom = v;}
         string get_prenom() { return prenom;}
        void set_prenom(string v) { prenom = v;}
         string get_type() { return type;}
        void set_type (string v) { type = v;}
         string get_code() { return code;}
        void set_code(string v) { code = v;}

};

#endif  //_PRESENTER_H
