//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UIViewer.h
//  @ Date : 23/08/2009
//  @ Author : 
//
//


#if !defined(_UIVIEWER_H)
#define _UIVIEWER_H

#include "IViewer.h"
#include "Presenter.h"

class UIViewer : public IViewer {
public:
	void UIViewer();
	void start();
	void callRequestUserCode();
	void callDisplayUserProfile();
	void displayListTypes(list<string> t);

        Presenter* get_presenter() { return presenter;}

        void ~UIViewer() { delete presenter;}
private:
	Presenter *presenter;
};

#endif  //_UIVIEWER_H
