/*
 * MonopolyFrame.java
 *
 * Created on 1 décembre 2001, 18:43
 */

package monopoly.gui;

import monopoly.*;

/**
 *
 * @author  letanou
 */
public class MonopolyFrame extends javax.swing.JFrame {
    private Monopoly game;

    /** Creates new form MonopolyFrame */
    public MonopolyFrame(Monopoly game) {
	this.game = game;
	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
	jNextButton = new javax.swing.JButton();
	jStartButton = new javax.swing.JButton();
	jStopButton = new javax.swing.JButton();

	getContentPane().setLayout(new java.awt.FlowLayout());

	setTitle("Monopoly Simulator");
	addWindowListener(new java.awt.event.WindowAdapter() {
	    public void windowClosing(java.awt.event.WindowEvent evt) {
		exitForm(evt);
	    }
	});

	jNextButton.setText("Next round");
	jNextButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jNextButtonActionPerformed(evt);
	    }
	});

	getContentPane().add(jNextButton);

	jStartButton.setText("Start");
	jStartButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jStartButtonActionPerformed(evt);
	    }
	});

	getContentPane().add(jStartButton);

	jStopButton.setText("Stop");
	jStopButton.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		jStopButtonActionPerformed(evt);
	    }
	});

	getContentPane().add(jStopButton);

	pack();
    }//GEN-END:initComponents

    private void jStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopButtonActionPerformed
	game.stopGame();
    }//GEN-LAST:event_jStopButtonActionPerformed

    private void jStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartButtonActionPerformed
	game.startGame();
    }//GEN-LAST:event_jStartButtonActionPerformed

    private void jNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextButtonActionPerformed
	game.nextRound();
    }//GEN-LAST:event_jNextButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
	System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
	Monopoly game = new Monopoly(100);
	game.addMonopolyListener(new SimpleMonopolyObserver());
	MonopolyPlayer p1 = new MonopolyPlayer("Yann", 1500, game, BuyingStrategyPool.getInstance().getRaiderStrategy());
	MonopolyPlayer p2 = new MonopolyPlayer("Olivier", 1500, game, BuyingStrategyPool.getInstance().getMoneySaverStrategy(100));
	game.addPlayer(p1);
	game.addPlayer(p2);
	new MonopolyFrame(game).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jNextButton;
    private javax.swing.JButton jStartButton;
    private javax.swing.JButton jStopButton;
    // End of variables declaration//GEN-END:variables

}
