//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Presenter.cpp
//  @ Date : 23/08/2009
//  @ Author : 
//
//

#include <list>
using namespace std;

#include "Presenter.h"
#include "IViewer.h"

void Presenter::Presenter(IViewer* v) {
    viewer = v;
}

void Presenter::start() {
    viewer->callRequestUserCode();

}

list<string> Presenter::loadListTypes() {
    list<string> types;
    types.add("Local");
    types.add("Domaine");
    return types;

}

bool Presenter::validate() {
    return (code.Length > 2);
}

void Presenter::codeInputEnded() {
    loadProfile(code);
    viewer->allDisplayUserProfile();

}

void Presenter::loadProfile(string code) {
    // appel aux services ... :) ... en fonction du code ...
    nom = "Son nom";
    prenom = "Son prénom";

}

