//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Presenter.cpp
//  @ Date : 23/08/2009
//  @ Author : 
//
//



#include "Presenter.h"
#include "IViewer.h"

Presenter::Presenter(IViewer* v) {
    viewer = v;
}

void Presenter::start() {
    viewer->callRequestUserCode();

}

vector<string> Presenter::loadListTypes() {
    vector<string> types;
	types.push_back("Local");
	types.push_back("Domaine");
    return types;

}

bool Presenter::validate() {
	return (code.length() > 2);
}

void Presenter::codeInputEnded() {
    loadProfile(code);
    viewer->callDisplayUserProfile();

}

void Presenter::loadProfile(string code) {
    // appel aux services ... :) ... en fonction du code ...
    nom = "Son nom";
    prenom = "Son prénom";

}

