//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UIViewer.cpp
//  @ Date : 23/08/2009
//  @ Author : 
//
//
#include <iostream>
#include <string>
using namespace std;

#include "UIViewer.h"

UIViewer::UIViewer() {
    presenter = new Presenter(this);
}

void UIViewer::start() {
    presenter->start();
}

void UIViewer::callRequestUserCode() {
    displayListTypes(presenter->loadListTypes());
    cout <<"Introduisez le code utilisateur:"<<endl;
    string rep;
    cin >> rep;
    presenter->set_code(rep) ;
    if (presenter->validate())
    {
        presenter->codeInputEnded();
    }
    else
    {
       cout <<"donnees non valides"<<endl;
       char c;
       cin >> c;
    }

}

void UIViewer::callDisplayUserProfile() {
    cout << "Utilisateur: " << presenter->get_code()<<endl;
    cout << "  Nom: "<< presenter->get_nom() <<endl;
    cout << "  Prénom: "<< presenter->get_prenom() <<endl;
    cout << "Appuyez sur ENTER pour quitter"<<endl;
    char c;
    cin >> c;

}

void UIViewer::displayListTypes(vector<string> t) {
    cout <<"Tapez le numéro du type choisi:"<<endl;
	for (unsigned int i=0; i<t.size(); i++)
    {
        cout <<i<<" "<< t[i]<<endl;
    }
    int rep;
    cin >> rep;
    presenter->set_type( t[rep]);

}

